export const flowSystem = {
  appState: {
    viewBackgroundColor: "transparent",
    theme: "light",
    language: "zh-CN",
  },
  elements: [
    // 中心主题矩形
    {
      id: "center",
      type: "rectangle",
      x: 400,
      y: 200,
      width: 120,
      height: 60,
      backgroundColor: "#DDA0DD",
      strokeColor: "#8B008B",
      fillStyle: "solid",
      strokeWidth: 2,
      roundness: { type: 3 },
    },
    // 中心主题文本
    {
      id: "center-text",
      type: "text",
      x: 410,
      y: 220,
      width: 100,
      height: 25,
      text: "心流系统",
      fontSize: 20,
      fontFamily: 1,
      textAlign: "center",
      verticalAlign: "middle",
      containerId: "center",
    },
    // 意识控制椭圆
    {
      id: "consciousness",
      type: "ellipse",
      x: 200,
      y: 100,
      width: 100,
      height: 50,
      backgroundColor: "#B0E0E6",
      strokeColor: "#4682B4",
      fillStyle: "solid",
      strokeWidth: 2,
    },
    // 意识控制文本
    {
      id: "consciousness-text",
      type: "text",
      x: 220,
      y: 115,
      width: 60,
      height: 25,
      text: "意识控制",
      fontSize: 16,
      fontFamily: 1,
      textAlign: "center",
      verticalAlign: "middle",
      containerId: "consciousness",
    },
    // 心流要素椭圆
    {
      id: "elements",
      type: "ellipse",
      x: 600,
      y: 100,
      width: 100,
      height: 50,
      strokeColor: "#228B22",
      backgroundColor: "#98FB98",
      fillStyle: "solid",
      strokeWidth: 2,
    },
    // 心流要素文本
    {
      id: "elements-text",
      type: "text",
      x: 620,
      y: 115,
      width: 60,
      height: 25,
      text: "心流要素",
      fontSize: 16,
      fontFamily: 1,
      textAlign: "center",
      verticalAlign: "middle",
      containerId: "elements",
    },
    // 目标设定椭圆
    {
      id: "goals",
      type: "ellipse",
      x: 200,
      y: 300,
      width: 100,
      height: 50,
      strokeColor: "#DAA520",
      backgroundColor: "#F0E68C",
      fillStyle: "solid",
      strokeWidth: 2,
    },
    // 目标设定文本
    {
      id: "goals-text",
      type: "text",
      x: 220,
      y: 315,
      width: 60,
      height: 25,
      text: "目标设定",
      fontSize: 16,
      fontFamily: 1,
      textAlign: "center",
      verticalAlign: "middle",
      containerId: "goals",
    },
    // 快乐来源椭圆
    {
      id: "happiness",
      type: "ellipse",
      x: 600,
      y: 300,
      width: 100,
      height: 50,
      strokeColor: "#FF69B4",
      backgroundColor: "#FFB6C1",
      fillStyle: "solid",
      strokeWidth: 2,
    },
    // 快乐来源文本
    {
      id: "happiness-text",
      type: "text",
      x: 620,
      y: 315,
      width: 60,
      height: 25,
      text: "快乐来源",
      fontSize: 16,
      fontFamily: 1,
      textAlign: "center",
      verticalAlign: "middle",
      containerId: "happiness",
    },
    // 连接线
    {
      id: "arrow-consciousness",
      type: "arrow",
      x: 400,
      y: 200,
      points: [
        [0, 0],
        [-100, -70],
      ],
      strokeColor: "#4682B4",
      strokeWidth: 2,
      startBinding: {
        elementId: "center",
        focus: -0.5,
        gap: 1
      },
      endBinding: {
        elementId: "consciousness",
        focus: 0.5,
        gap: 1
      },
    },
    {
      id: "arrow-elements",
      type: "arrow",
      x: 520,
      y: 200,
      points: [
        [0, 0],
        [80, -70],
      ],
      strokeColor: "#228B22",
      strokeWidth: 2,
      startBinding: {
        elementId: "center",
        focus: 0.5,
        gap: 1
      },
      endBinding: {
        elementId: "elements",
        focus: 0.5,
        gap: 1
      },
    },
    {
      id: "arrow-goals",
      type: "arrow",
      x: 400,
      y: 260,
      points: [
        [0, 0],
        [-100, 70],
      ],
      strokeColor: "#DAA520",
      strokeWidth: 2,
      startBinding: {
        elementId: "center",
        focus: -0.5,
        gap: 1
      },
      endBinding: {
        elementId: "goals",
        focus: 0.5,
        gap: 1
      },
    },
    {
      id: "arrow-happiness",
      type: "arrow",
      x: 520,
      y: 260,
      points: [
        [0, 0],
        [80, 70],
      ],
      strokeColor: "#FF69B4",
      strokeWidth: 2,
      startBinding: {
        elementId: "center",
        focus: 0.5,
        gap: 1
      },
      endBinding: {
        elementId: "happiness",
        focus: 0.5,
        gap: 1
      },
    },
    // 为意识控制添加要点
    {
      id: "consciousness-points",
      type: "text",
      x: 150,
      y: 40,
      width: 200,
      height: 60,
      text: "• 意识是可感知可引导的\n• 注意力决定意识内容\n• 资讯中性，阐释决定好坏",
      fontSize: 14,
      fontFamily: 1,
      textAlign: "left",
      verticalAlign: "middle",
    },
    // 为心流要素添加要点
    {
      id: "elements-points",
      type: "text",
      x: 550,
      y: 40,
      width: 200,
      height: 60,
      text: "• 全神贯注+自我进步\n• 明确目标、适度挑战\n• 即时反馈、沉浸感",
      fontSize: 14,
      fontFamily: 1,
      textAlign: "left",
      verticalAlign: "middle",
    },
    // 为目标设定添加要点
    {
      id: "goals-points",
      type: "text",
      x: 150,
      y: 350,
      width: 200,
      height: 60,
      text: "• 精简目标减少冲突\n• 找到真正重要的事\n• 平衡挑战与能力",
      fontSize: 14,
      fontFamily: 1,
      textAlign: "left",
      verticalAlign: "middle",
    },
    // 为快乐来源添加要点
    {
      id: "happiness-points",
      type: "text",
      x: 550,
      y: 350,
      width: 200,
      height: 60,
      text: "• 宇宙不以人类为中心\n• 快乐源于心灵阐释\n• 控制意识才能控制体验",
      fontSize: 14,
      fontFamily: 1,
      textAlign: "left",
      verticalAlign: "middle",
    },
    // 添加连接说明
    {
      id: "consciousness-connection",
      type: "text",
      x: 280,
      y: 130,
      width: 120,
      height: 40,
      text: "掌控意识",
      fontSize: 12,
      fontFamily: 1,
      textAlign: "center",
      strokeColor: "#4682B4",
    },
    {
      id: "elements-connection",
      type: "text",
      x: 500,
      y: 130,
      width: 120,
      height: 40,
      text: "构建心流",
      fontSize: 12,
      fontFamily: 1,
      textAlign: "center",
      strokeColor: "#228B22",
    },
    {
      id: "goals-connection",
      type: "text",
      x: 280,
      y: 270,
      width: 120,
      height: 40,
      text: "找到方向",
      fontSize: 12,
      fontFamily: 1,
      textAlign: "center",
      strokeColor: "#DAA520",
    },
    {
      id: "happiness-connection",
      type: "text",
      x: 500,
      y: 270,
      width: 120,
      height: 40,
      text: "获得快乐",
      fontSize: 12,
      fontFamily: 1,
      textAlign: "center",
      strokeColor: "#FF69B4",
    },
  ],
  UIOptions: {
    canvasActions: {
      loadScene: false,
      saveAsImage: true,
      saveToActiveFile: false,
      export: false,
      toggleTheme: false,
    },
    defaultSidebarDockedPreference: true,
  }
}; 